# source: https://www.drupal.org/node/1136336
parameters:
    countries:
        DE: Deutschland
        AT: Österreich
        CH: Schweiz
        LU: Luxemburg
        AF: Afghanistan
        EG: Ägypten
        AX: Åland
        AL: Albanien
        DZ: Algerien
        AS: Amerikanisch-Samoa
        AD: Andorra
        AO: Angola
        AI: Anguilla
        AQ: Antarktis
        AG: Antigua/Barbuda
        GQ: Äquatorialguinea
        AR: Argentinien
        AM: Armenien
        AW: Aruba
        AZ: Aserbaidschan
        ET: Äthiopien
        AU: Australien
        BS: Bahamas
        BH: Bahrain
        BD: Bangladesh
        BB: Barbados
        BE: Belgien
        BZ: Belize
        BJ: Benin
        BM: Bermuda
        BT: Bhutan
        BO: Bolivien
        BA: Bosnien/Herzegowina
        BW: Botsuana
        BV: Bouvetinsel
        BR: Brasilien
        BN: Brunei Darussalam
        BG: Bulgarien
        BF: Burkina Faso
        BI: Burundi
        CV: Cabo Verde
        CL: Chile
        CN: China
        CK: Cookinseln
        CR: Costa Rica
        CU: Cuba
        DM: Dominica
        DO: Dominikanische Republik
        DJ: Dschibuti
        DK: Dänemark
        EC: Ecuador
        SV: El Salvador
        CI: Elfenbeinküste
        ER: Eritrea
        EE: Estland
        FK: Falklandinseln
        FJ: Fidschi
        FI: Finnland
        FR: Frankreich
        GF: Französisch-Guayana
        PF: Französisch-Polynesien
        TF: Französische Südpolarterritorien
        FO: Färöer
        GA: Gabun
        GM: Gambia
        GE: Georgien
        GH: Ghana
        GI: Gibraltar
        GD: Grenada
        GR: Griechenland
        GB: Großbritannien
        GL: Grönland
        GP: Guadeloupe
        GU: Guam
        GT: Guatemala
        GG: Guernsey
        GW: Guinea-Bissau
        GN: Guinea
        GY: Guyana
        HT: Haiti
        HM: Heard und McDonaldinseln
        HN: Honduras
        HK: Hong Kong
        IN: Indien
        ID: Indonesien
        IQ: Irak
        IR: Iran
        IE: Irland
        IS: Island
        IM: Isle Of Man
        IL: Israel
        IT: Italien
        JM: Jamaika
        JP: Japan
        YE: Jemen
        JE: Jersey
        JO: Jordanien
        VI: Jungferninseln, Amerikanische
        VG: Jungferninseln, Britische
        KY: Kaimaninseln
        KH: Kambodscha
        CM: Kamerun
        CA: Kanada
        KZ: Kasachstan
        KE: Kenia
        KG: Kirgisistan
        KI: Kiribati
        CC: Kokosinseln
        CO: Kolumbien
        KM: Komoren
        CG: Kongo
        HR: Kroatien
        KW: Kuwait
        LA: Laos
        LS: Lesotho
        LV: Lettland
        LB: Libanon
        LR: Liberia
        LY: Libyen
        LI: Liechtenstein
        LT: Litauen
        MO: Macao
        MG: Madagaskar
        MW: Malawi
        MY: Malaysia
        MV: Maldiven
        ML: Mali
        MT: Malta
        MH: Marshallinseln
        MQ: Martinique
        MR: Mauretanien
        MU: Mauritius
        YT: Mayotte
        MK: Mazedonien
        MX: Mexiko
        FM: Mikronesien
        MD: Moldawien
        MC: Monaco
        MN: Mongolei
        ME: Montenegro
        MS: Montserrat
        MA: Morokko
        MZ: Mosambik
        MM: Myanmar
        NA: Namibia
        NR: Nauru
        NP: Nepal
        NC: Neukaledonien
        NZ: Neuseeland
        NI: Nicaragua
        NL: Niederlande
        AN: Niederländische Antillen
        NG: Nigeria
        NE: Niger
        NU: Niue
        KP: Nordkorea
        NF: Norfolkinsel
        NO: Norwegen
        MP: Nördliche Marianen
        OM: Oman
        PK: Pakistan
        PW: Palau
        PS: Palestina
        PA: Panama
        PG: Papua-Neuguinea
        PY: Paraguay
        PE: Peru
        PH: Philippinen
        PN: Pitcairninseln
        PL: Polen
        PT: Portugal
        PR: Puerto Rico
        QA: Qatar
        RW: Ruanda
        RO: Rumänien
        RU: Russland
        RE: Réunion
        SB: Salomonen
        ZM: Sambia
        WS: Samoa
        SM: San Marino
        SA: Saudi-Arabien
        SE: Schweden
        SN: Senegal
        RS: Serbien
        SC: Seychellen
        SL: Sierra Leone
        ZW: Simbabwe
        SG: Singapur
        SK: Slowakische Republik
        SI: Slowenien
        SO: Somalia
        ES: Spanien
        LK: Sri Lanka
        BL: St. Barthélemy
        SH: St. Helena
        KN: St. Kitts/Nevis
        LC: St. Lucia
        MF: St. Martin
        PM: St. Pierre/Miquelon
        VC: St. Vincent/Die Grenadinen
        SD: Sudan
        SR: Surinam
        SJ: Svalbard/Jan Mayen
        SZ: Swasiland
        SY: Syrien
        ST: São Tomé/Príncipe
        ZA: Südafrika
        GS: Südgeorgien/Südlichen Sandwichinseln
        KR: Südkorea
        TJ: Tadschikistan
        TW: Taiwan
        TZ: Tansania
        TH: Thailand
        TL: Timor-Leste
        TG: Togo
        TK: Tokelau
        TO: Tonga
        TT: Trinidad und Tobago
        TD: Tschad
        CZ: Tschechoslowakei
        TN: Tunisien
        TM: Turkmenistan
        TC: Turks- und Caicosinseln
        TV: Tuvalu
        TR: Türkei
        UG: Uganda
        UA: Ukraine
        HU: Ungarn
        UM: United States Minor Islands
        UY: Uruguay
        US: USA
        UZ: Usbekistan
        VU: Vanuatu
        VA: Vatikanstadt
        VE: Venezuela
        AE: Vereinigte Arabische Emirate
        VN: Vietnam
        WF: Wallis/Futuna
        CX: Weihnachtsinsel
        BY: Weißrussland
        EH: Westsahara
        CF: Zentralafrikanische Republik
        CY: Zypern
