twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    number_format:
        decimals: 2
        decimal_point: ','
        thousands_separator: '.'
    date:
        timezone: Europe/Berlin
