version: "3.6"
services:
  "db":
    image: "mysql:5.7"
    ports:
      - "3392:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=accownting"
      - "MYSQL_USER=accownting"
      - "MYSQL_PASSWORD=accownting"
    volumes:
      - "mysql:/var/lib/mysql"
    networks:
      - "internal"

  "app":
    build:
      context: "./"
      dockerfile: "./Dockerfile.dev"
    ports:
      - "8083:80"
    volumes:
      - "./:/var/www"
      - "./vendor/:/var/www/vendor/:cached"
    networks:
      - "internal"
    tmpfs:
      - "/var/www/var/"

networks:
  "internal":

volumes:
  mysql:
